"""Verified user-facing ASARK routes and their navigation labels."""

SITE_CONTEXT = {
    "Home": "/",
    "Home (index.html)": "/index.html",
    "Technology": "/technology.html",
    "AI Technology": "/ai-technology.html",
    "Semiconductor Systems": "/semiconductor.html",
    "VLSI Design": "/vlsi.html",
    "What is VLSI?": "/what-is-vlsi.html",
    "Computing Technology": "/computing.html",
    "Processor Technology": "/processor.html",
    "Graphics Card Technology": "/graphics-card.html",
    "Space Technology": "/space.html",
    "Commercial Space Infrastructure": "/commercial-space-infrastructure.html",
    "Market Technology": "/market-technology.html",
    "ASARK Journal": "/blogs.html",
    "AI Technology Journal": "/journal/ai-technology-future.html",
    "Market Technology Journal": "/journal/market-technology-future.html",
    "Semiconductor Technology Journal": "/journal/semiconductor-technology-future.html",
    "Space Technology Journal": "/journal/space-technology-future.html",
    "Autonomous AI Systems": "/evolution-of-autonomous-ai-systems.html",
    "Art and Design": "/art-design.html",
    "Explore ASARK": "/explore.html",
    "Stories": "/stories.html",
    "Culture and Future": "/culture-future.html",
    "Ambient Lighting Guide": "/guides/ambient-lighting.html",
    "Coffee Ritual Guide": "/guides/coffee-ritual.html",
    "Intelligent Home Guide": "/guides/intelligent-home-foundation.html",
    "About ASARK": "/about.html",
    "Contact ASARK": "/contact.html",
    "Privacy Policy": "/privacy.html",
    "Terms and Conditions": "/terms.html",
}

PAGE_TITLES = {path: title for title, path in SITE_CONTEXT.items()}

PAGE_SECTIONS = {
    "/": "Home",
    "/index.html": "Home",
    "/technology.html": "Technology",
    "/ai-technology.html": "Artificial Intelligence",
    "/semiconductor.html": "Semiconductors",
    "/vlsi.html": "VLSI Design",
    "/what-is-vlsi.html": "VLSI Design",
    "/computing.html": "Computing",
    "/processor.html": "Computing",
    "/graphics-card.html": "Computing",
    "/space.html": "Space Technology",
    "/commercial-space-infrastructure.html": "Space Technology",
    "/market-technology.html": "Market Technology",
    "/blogs.html": "Journal",
    "/journal/ai-technology-future.html": "Journal",
    "/journal/market-technology-future.html": "Journal",
    "/journal/semiconductor-technology-future.html": "Journal",
    "/journal/space-technology-future.html": "Journal",
    "/art-design.html": "Art and Design",
    "/explore.html": "Explore ASARK",
    "/evolution-of-autonomous-ai-systems.html": "AI and Autonomy",
    "/about.html": "About ASARK",
    "/contact.html": "Contact ASARK",
    "/privacy.html": "Privacy Policy",
    "/terms.html": "Terms and Conditions",
    "/culture-future.html": "Culture and Future",
    "/stories.html": "Stories and Guides",
    "/guides/ambient-lighting.html": "Practical Guides",
    "/guides/coffee-ritual.html": "Practical Guides",
    "/guides/intelligent-home-foundation.html": "Practical Guides",
}
